name: sportsbook
version: "1.0"
profile: sportsbook

models:
  sportsbook:
    staging:
      +schema: staging
      +materialized: view

    mart:
      +schema: mart
      +materialized: table

      analytics:
        +schema: report
        +materialized: view
